---
name: "sinatra"
runtimes:
  - ruby18:
      default: true
      environment:
       bundle_gemfile:
  - ruby19:
      environment:
       bundle_gemfile:
  - myruntime:
       default: false
detection:
  - "*.rb": "require\\s+'sinatra'|require\\s+\"sinatra\"" # .rb files in the root dir containing a require?
  - "config.ru": false # use rack if it detects a config.ru
  - "config/environment.rb": false # and config/environment.rb must not exist

# vim: filetype=yaml
