source 'http://rubygems.org'

# Rails itself
gem 'rails', '~> 3.0.14'
# Message bus
gem 'nats', :require => 'nats/client'

# VCAP common components
gem 'vcap_common', :require => ['vcap/common', 'vcap/component'], :git => 'https://github.com/cloudfoundry/vcap-common.git', :ref => '1dca468ec0'
gem 'vcap_logging', :require => ['vcap/logging'], :git => 'https://github.com/cloudfoundry/common.git', :ref => 'e36886a1'
gem 'vcap_staging', '~> 0.1.62', :git => 'https://github.com/cloudfoundry/vcap-staging.git', :ref => '74d89654'
gem 'cf-uaa-client', '~> 1.0', :git => 'https://github.com/cloudfoundry/uaa.git', :ref => 'dad29c90'

# For queuing staging tasks
gem 'em-hiredis'
gem 'stager-client', '~> 0.0.2', :git => 'https://github.com/cloudfoundry/stager-client.git'

# Databases
gem 'sqlite3'
group :production do
  gem 'pg'
  # Get blocking postgres working for now, try nonblocking drivers when we have more time
  # gem 'postgres-pr', '0.6.3'
  # gem 'em_postgresql', '0.3.0'
end

# EventMachine and async support
gem 'eventmachine', :git => 'https://github.com/cloudfoundry/eventmachine.git', :branch => 'release-0.12.11-cf'
gem 'thin'
gem 'em-http-request', '~> 1.0.0.beta.3', :require => 'em-http'
gem 'em-redis', '~> 0.3.0', :require => nil
gem 'rack-fiber_pool', '~> 0.9.1', :require => nil

# Support libraries
gem 'yajl-ruby', '~> 0.8.3'
gem 'nokogiri', '~> 1.4.4'
gem 'bcrypt-ruby', '~> 2.1.4'
gem 'ruby-hmac', '~> 0.4.0', :require => 'hmac-sha1'
gem 'SystemTimer', '~> 1.2', :platforms => :mri_18
gem 'uuidtools', '~> 2.1.2'
gem 'rest-client', '~> 1.6.7'

# rspec-rails is outside the 'test' group in order to consistently provide Rake tasks.
gem 'rspec-rails', '>= 2.4.1'
group :test do
  gem 'rspec', '>= 2.4.0', :require => nil
  gem 'rcov'
  gem 'mocha'
  gem 'ci_reporter'
  gem 'sinatra'  # For service gateway shims
  gem 'delorean'
end

